### ISSUE TITLE
Support for Debian 10

### ISSUE THREAD

**Issue by frantsao** [idealista/consul_role#46]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
We need support for Debian 10 in this role.
We also must update requirements (Ansible, molecule, etc.).

**Comment by xtianae7** [comment]
Release 1.4.1 which added **private_tmp_service** variable, is correct, but the variable name is very generic, it should be changed to something like **consul_private_tmp**

**Comment by caldito** [comment]
@xtianae7 I will include this in the next fix release
